config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :words do
      resources :definitions
    end
  end

  root :to => 'home#index'
  # get '/user/profile' => "users/show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/definition.rb
class Definition<ActiveRecord::Base
  belongs_to :word
  validates :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :words
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :authentication_keys => [:username]
  devise :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def email_required?
    false
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/models/word.rb
class Word<ActiveRecord::Base
  belongs_to :user
  has_many :definitions
  validates :img, :presence => true
  validates :title, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  # filter in Flickr version
  # before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :avatar])
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(:username, :password, :password_confirmation, :current_password)
    }
  end
end

app/controllers/definitions_controller.rb
class DefinitionsController<ApplicationController

  def show
    @user = User.find(params[:user_id])
    @word = Word.find(params[:word_id])
    @definition = Definition.find(params[:id])
    render :show
  end

  def new
    @user = User.find(params[:user_id])
    @word = Word.find(params[:word_id])
    @definition = @word.definitions.new
    render :new
  end

  def create
    @user = User.find(params[:user_id])
    @word = Word.find(params[:word_id])
    @definition = @word.definitions.new(definition_params)

    if @definition.save
      flash[:notice] = "Definition successfully added!"
      respond_to do |format|
        format.html { redirect_to user_word_path(@user) }
        format.js
      end
      # redirect_to user_words_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])

    @word = Word.find(params[:word_id])
    @definition = Definition.find(params[:id])
    render :edit
  end

  def update
    @word = Word.find(params[:word_id])
    @definition = Definition.find(params[:id])
    @user = User.find(params[:user_id])
    if @definition.update(definition_params)
      flash[:notice] = "Definition successfully editted"
      redirect_to user_word_path(@user, @word)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @word = Word.find(params[:word_id])
    @definition = Definition.find(params[:id])
    @definition.destroy
    flash[:notice] = "Definition successfully deleted"
    redirect_to user_word_path(@user, @word)
  end

private
  def definition_params
    params.require(:definition).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController<ApplicationController
  def index

  end
#
private
  def sign_up_params
    params.require(:user).permit(:email, :avatar, :password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # private
  # def sign_up_params
  #   params.require(:user).permit(:email, :avatar, :password, :password_confirmation)
  # end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    UserMailer.example(User.new(email: 'katka.karolcikova@gmail.com')).deliver
    @users = User.all
  end

  def show
    @user = current_user
    render :profile
  end

  def edit
    @user.update(user_params)
    @user.update(image_params)
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(image_params)
    redirect_to user_path(@user)

  end

private
  def image_params
    params.require(:user).permit(:avatar)
  end

end

app/controllers/words_controller.rb
class WordsController<ApplicationController
  def index
    @words = Word.all
    @user = User.find(params[:user_id])
    render :index
  end

  def show
    @word = Word.find(params[:id])
    @user = User.find(params[:user_id])
    render :show
  end

  def new
    @user = User.find(params[:user_id])
    @word = Word.new
    render :new
  end

  def create
    @word = Word.new(word_params)
    @word.user = User.find(params[:user_id])
    if @word.save
      flash[:notice] = "Word successfully added!"
      redirect_to user_words_path(current_user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @word = Word.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:user_id])
    @word = current_user.words.find(params[:id])
    if @word.update(word_params)
      flash[:notice] = "Word successfully editted!"
      redirect_to user_word_path(current_user, @word)
    else
      render :edit
    end
  end

  def destroy
    # @user = User.find(params[:user_id])
    @word = Word.find(params[:id])
    @word.destroy
    flash[:notice] = "Word successfully deleted!"
    redirect_to user_words_path(current_user)
  end

private
  def word_params
    params.require(:word).permit(:img, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/definitions/_definition.html.erb
<li ><%=link_to definition.content, user_word_definition_path(@user, @word, definition) %></li>

app/views/definitions/_form.html.erb
<%= render "layouts/errors", :object => @definition %>

<%=form_for [@user, @word, @definition], remote: true do |f| %>
  <%= f.label :content, "Meaning/Definition" %>
  <%= f.text_field :content, title: "meaning_def" %>
  <%= f.submit "Save"%>
<%end%>

app/views/definitions/create.js.erb
// alert('Here');
$('#new_definition').hide();
$('#new_definition_link').show();
$('#results').append("<%= j render 'definition', definition: @definition %>");

app/views/definitions/edit.html.erb
<h2>Edit definition</h2>
<%= render 'form' %>

<%= link_to "Return to word", user_word_path(@user, @word) %>
<%= link_to "Return to list of words", user_words_path(current_user) %>

app/views/definitions/new.html.erb
<h2>New definition</h2>
<%= render 'form' %>

<%= link_to "Return to word", user_word_path(@user, @word) %>

<%= link_to "Return to list of words", user_words_path(current_user) %>

app/views/definitions/new.js.erb
// alert('Here');
$('#new_definition_link').hide().after('<%= j render("form") %>');

app/views/definitions/show.html.erb
<h2><%=@definition.content%><%= link_to "Edit", edit_user_word_definition_path(@user, @word, @definition) %></h2>



<%= link_to "Delete definition", user_word_definition_path(@user, @word, @definition), :data => {:confirm => "You sure?",                             :method => "delete"} %>
<%= link_to "Return to word", user_word_path(@user, @definition) %>

<%= link_to "Return to list of words", user_words_path(current_user) %>

app/views/home/index.html.erb
<h3>Tech Flashcards</h3>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechFlashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--test  -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Tech Flashcards", root_path, class:"navbar-brand"%>
          </div>

          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              <!-- <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Page 1-1</a></li>
                  <li><a href="#">Page 1-2</a></li>
                  <li><a href="#">Page 1-3</a></li>
                </ul>
              </li> -->
              <% if user_signed_in? %>
                <!-- <li><a href="#">Dictionary</a></li> -->
                <li><%= link_to ' My Words', user_words_path(current_user)%></li>
                <li><%= link_to 'Add a new word', new_user_word_path(current_user)%></li>
              <%end%>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <% if current_user.name? %>
                    <li class = 'signin_as_margin'><span>Signed in as <%= link_to current_user.name, user_path(current_user)%></span></li>
                <%else%>

                  <li class = 'signin_as_margin'><span>Signed in as <%= link_to current_user.username, user_path(current_user)%></span></li>
                <%end%>

                <li class= "navbar-collapse"><%= link_to destroy_user_session_path, method: :delete do %>
                  <span class= "glyphicon glyphicon-log-out"></span>Sign Out
                <%end%></li>
              <%else%>

              <li><%= link_to new_user_registration_path do %>
                <span class= "glyphicon glyphicon-log-out"></span>Sign Up
              <%end%></li>

                <li><%= link_to new_user_session_path do%>
                  <span class= "glyphicon glyphicon-log-in"></span>Sign In
                <%end%></li>

                <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
              <%end%>
            </ul>
          </div>
        </div>
      </nav>

      <div class="jumbotron">
        <h1>Hello, world!</h1>
          <br>
          <br>
          <br>
          <br>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
      </div>
      <div class="container_under_jumbotrone">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/profile.html.erb
<% if @user.name? %>
  <h2>Name:<%= current_user.name%></h2>
<%else%>
  <h2>Username : <%= current_user.username %></h2>
<%end%>
<h2>Email : <%= current_user.email %></h2>

<% if @user.image? %>
  <img src="<%= current_user.image %>" />
<%else%>
  <% if @user.avatar.exists? %>
    <%= image_tag @user.avatar.url(:medium), class: "img-circle" %>
  <% else %>
  <h3>You have not uploaded a photo, let's change that</h3>
    <%= form_for @user do |f| %>
      <div class="field">
        <%= f.label :avatar %><br />
        <%= f.file_field :avatar %>
        <%= f.submit "Add Image" %>
      </div>
    <% end %>
  <% end %>
  <%= link_to "Edit Profile", edit_user_registration_path(@user)%>
<% end %>

<p>Unhappy? Cancel my account <%= button_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %></p>

app/views/words/_form.html.erb
<%= render "layouts/errors", :object => @word %>

<%=form_for [@user, @word] do |f| %>
  <%= f.label :img, "Img" %>
  <%= f.text_field :img %>
  <%= f.label :title, "Word" %>
  <%= f.text_field :title %>
  <%= f.submit %>
<%end%>

app/views/words/edit.html.erb
<h2>Edit word</h2>
<%= render 'form' %>

<%= link_to "Return to list of words", user_words_path(current_user) %>

app/views/words/index.html.erb
<h2>Words</h2>

<ul>
  <% @words.each do |word| %>
    <li><%= link_to word.title, user_word_path(@user, word) %></li>
  <%end%>
</ul>

app/views/words/new.html.erb
<h2>New word</h2>
<%= render 'form' %>

app/views/words/show.html.erb
<h1><%=@word.title %></h1>


<img src="<%= @word.img %>" alt='picture of <%=@word.title %>' />
  <h3>Definitions listed below</h3>
  <ol id ="results">
    <% if @word.definitions.any? %>
      <% @word.definitions.each do |definition| %>
        <%= render "definitions/definition", definition: definition %>
      <%end%>
    <%end%>
  </ol>

<%= link_to "Add a new definition", new_user_word_definition_path(@user, @word), remote: true, id: "new_definition_link"%>
<div class="btn-group" role="group">
  <button type="button" class="btn btn-default"><%= link_to "Edit", edit_user_word_path %></button>
  <button type="button" class="btn btn-default"><%= link_to "Delete", user_word_path(@word), :data => {:confirm => "You sure?", :method => "delete"} %></button>
</div>
<hr>
<%= link_to "Return to list of words", user_words_path(current_user) %>